/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#802c25",
        "surface-variant": "#e4e3db",
        "surface-container": "#f0eee6",
        "tertiary-fixed": "#ffdad5",
        "on-tertiary-fixed": "#410001",
        "on-secondary-fixed-variant": "#574500",
        "surface": "#fbf9f1",
        "secondary": "#735c00",
        "tertiary": "#611611",
        "primary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb4aa",
        "secondary-fixed": "#ffe088",
        "on-primary-fixed": "#410005",
        "on-primary-container": "#ff9d98",
        "on-tertiary-fixed-variant": "#7e2b23",
        "on-error-container": "#93000a",
        "primary": "#6b000e",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fed65b",
        "surface-dim": "#dcdad2",
        "primary-container": "#960018",
        "surface-container-high": "#eae8e0",
        "primary-fixed-dim": "#ffb3af",
        "on-surface": "#1b1c17",
        "surface-container-highest": "#e4e3db",
        "outline-variant": "#e2bebb",
        "inverse-primary": "#ffb3af",
        "error": "#ba1a1a",
        "surface-container-low": "#f5f4ec",
        "on-secondary-fixed": "#241a00",
        "outline": "#8e706e",
        "on-secondary-container": "#745c00",
        "inverse-surface": "#30312c",
        "on-primary-fixed-variant": "#930017",
        "background": "#fbf9f1",
        "on-background": "#1b1c17",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#5a403f",
        "surface-tint": "#b6212b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ff9d92",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#e9c349",
        "on-primary": "#ffffff",
        "surface-bright": "#fbf9f1",
        "inverse-on-surface": "#f3f1e9"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      fontFamily: {
        "serif": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "headline": ["Noto Serif", "serif"],
      }
    },
  },
  plugins: [],
}